### ISSUE TITLE
Is this demo ready?

### ISSUE THREAD

**Issue by daveeel** [copleykj/socialize-messaging-demo#1]
Just tried run. Registered 2 users from 2 browsers. Browsers are always black and source has empty html. Is the demo runnable by itself or need special config?

**Comment by copleykj** [comment]
It's not really in a state to just run it. It was built as a way to debug another devs issues they were having with the package. I'm working now on a demo that will incorporate all of the socialize packages into one cohesive social network style demo. I expect it to take another couple weeks, maybe a month depending on the amount of time I can allocate to work on it.

**Comment by daveeel** [comment]
Thanks, looking forward to it.

**Comment by rubenlpz** [comment]
Did the working demo finally come?  Same issue here with black screen after login.
Regards
